// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txrkimtlugynnezdbrnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cmtpbXRsdWd5bm5lemRicm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTk2ODksImV4cCI6MjA2NDA5NTY4OX0.JCtDkz7aYKXS8NWLxQez9xLmHNHgrQ6TTw-ABDrsEmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);